name: Test

on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Test
        run: |
          yarn test --base=origin/$GITHUB_BASE_REF
