name: Type Check

on:
  merge_group:
    types: [checks_requested]
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: build-${{ github.event.pull_request.number || github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  type-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Run Type Check
        if: github.ref != 'refs/heads/main'
        run: |
          yarn type-check --base=origin/$GITHUB_BASE_REF

      - name: Run Type Check
        if: github.ref == 'refs/heads/main'
        run: |
          yarn type-check
